spring:
  application:
    name: GATEWAY-SERVICE
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: question-service
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/questions/**

        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/feedback/**

        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stockHistory/**

        - id: portfolio-service
          uri: lb://PORTFOLIO-SERVICE
          predicates:
            - Path=/portfolio/**

        - id: watchlist-service
          uri: lb://watchlist
          predicates:
            - Path=/watchlist/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
